# Generated by Django 4.2 on 2023-06-30 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 20, 40, 48, 859229)),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(default=' not paid', max_length=250, null=True),
        ),
    ]
