# Generated by Django 4.2.2 on 2023-07-01 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_order_delivery_date_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 8, 4, 6, 15, 723231)),
        ),
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
