# Generated by Django 4.2.2 on 2023-07-01 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_order_delivery_date_alter_order_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 8, 5, 30, 11, 242955)),
        ),
    ]
