# Generated by Django 4.2.2 on 2023-07-01 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_alter_order_delivery_date_alter_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
    ]
