# Generated by Django 4.2 on 2023-08-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='refund_status',
            field=models.CharField(choices=[('requested', 'return requested'), ('intiated', 'refund initiated'), ('refunded', 'refunded')], default='requested', max_length=20),
        ),
    ]
