# Generated by Django 4.2 on 2023-06-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mobilenumber',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
