# Generated by Django 4.2 on 2023-06-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_account_mobilenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
