# Generated by Django 4.2 on 2023-06-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_account_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
