# Generated by Django 4.2 on 2023-07-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
