# Generated by Django 4.2 on 2023-06-21 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('house_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('post_office', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.BigIntegerField()),
                ('mobile', models.BigIntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
