# Generated by Django 4.2.2 on 2023-06-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='first_name',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='address',
            name='house_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='post_office',
        ),
    ]
