# Generated by Django 4.2.2 on 2023-06-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_rename_first_name_address_fullname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='District',
            new_name='district',
        ),
    ]
