# Generated by Django 4.2 on 2023-07-08 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_coupon_alter_productoffers_product_offer_percentage'),
        ('cart', '0003_cartitems_variant_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.coupon'),
        ),
    ]
