# Generated by Django 4.2 on 2023-07-08 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_coupun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='coupun',
            new_name='coupon',
        ),
    ]
