# Generated by Django 4.2 on 2023-06-14 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_variant_image_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AddField(
            model_name='productimage',
            name='variant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='products.variant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='variant_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='variant_images'),
        ),
    ]
