# Generated by Django 4.2 on 2023-06-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
