# Generated by Django 4.2 on 2023-07-04 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_variantimage_delete_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screensize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screensize', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='variant',
            name='screensize',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.screensize'),
        ),
    ]
