# Generated by Django 4.2 on 2023-07-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_screensize_variant_screensize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screensize',
            name='screensize',
            field=models.CharField(max_length=30),
        ),
    ]
