# Generated by Django 4.2 on 2023-07-07 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productoffers_categoryoffers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffers',
            name='category_offer_percentage',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)]),
        ),
    ]
