# Generated by Django 4.2 on 2023-07-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_coupon_alter_productoffers_product_offer_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
    ]
