# Generated by Django 4.2 on 2023-07-10 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_coupon_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='user',
        ),
    ]
